// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-Wl55gkyx27Az92oLiPV0dUfQLKRDeNk',
    appId: '1:488355088986:web:70ec44a1833c022bbce663',
    messagingSenderId: '488355088986',
    projectId: 'flutter-demo-eaafd',
    authDomain: 'flutter-demo-eaafd.firebaseapp.com',
    storageBucket: 'flutter-demo-eaafd.appspot.com',
    measurementId: 'G-DTLFCPMLYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn0_X4rMzTCullfLslt_loyXiyrvi2e4k',
    appId: '1:488355088986:android:0f7ed937f52bd69bbce663',
    messagingSenderId: '488355088986',
    projectId: 'flutter-demo-eaafd',
    storageBucket: 'flutter-demo-eaafd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxCGN7zPR8njXRkDrfHaKPbUyjMmnWCao',
    appId: '1:488355088986:ios:c4c427afdb61b3ddbce663',
    messagingSenderId: '488355088986',
    projectId: 'flutter-demo-eaafd',
    storageBucket: 'flutter-demo-eaafd.appspot.com',
    iosBundleId: 'com.example.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxCGN7zPR8njXRkDrfHaKPbUyjMmnWCao',
    appId: '1:488355088986:ios:e1a0e1aeb457b0e1bce663',
    messagingSenderId: '488355088986',
    projectId: 'flutter-demo-eaafd',
    storageBucket: 'flutter-demo-eaafd.appspot.com',
    iosBundleId: 'com.example.demo1.RunnerTests',
  );
}
